In [1]:
import numpy as np
import pandas as pd

In [14]:
import pandas as pd

subs = pd.read_csv("C:/Users/thera/Downloads/subs.csv")
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [67]:
import pandas as pd
#you can also save data as df and virat as you like

virat = pd.read_csv("C:/Users/thera/Downloads/kohli_ipl.csv",index_col="match_no")
virat

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [26]:
movies = pd.read_csv("C:/Users/thera/Downloads/bollywood.csv",index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [ ]:
# Important Series methods
# head and tail #head give start 5 rows and tails give last 5 rows
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [29]:
virat.head()

          runs
match_no
1            1
2           23
3           13
4           12
5            1

In [31]:
# subs.tail()
virat.tail()

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [33]:
virat.tail(10)

          runs
match_no
206          0
207          0
208          9
209         58
210         30
211          0
212         20
213         73
214         25
215          7

In [42]:
movies.sample(5) # this give randam data

                                      lead
movie
Jaane Kahan Se Aayi Hai    Priyanka Chopra
68 Pages                     Mouli Ganguly
Mastram                        Rahul Bagga
What the Fish            Manu Rishi Chadha
D (film)                     Randeep Hooda

In [ ]:
# value_count --> movies

movies.value_counts() #it give a number for decending order

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Kashmira Shah        1
Kartik Elangovan     1
Karisma Kapoor       1
Karan Sharma         1
Zulfi Sayed          1
Name: count, Length: 566, dtype: int64

In [68]:
# sort_values --> inplace
virat.sort_values(by="match_no")
                #   ascending=False).head(1).values[0]

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [75]:
# sort_index --> inplace--> movies

movies.sort_index() #it is sort alpabet wise like a,b,c,d etc

movies.sort_index(inplace=True) # inplace=True change the original datasets
# movies.sort_index(ascending=False,inplace=True)

In [76]:
movies

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

In [77]:
# Series Math Methods
 # count give a total number of value
virat.count()

runs    215
dtype: int64